version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - Aedius
  ignore:
  - dependency-name: libc
    versions:
    - 0.2.84
    - 0.2.85
    - 0.2.86
    - 0.2.87
    - 0.2.88
    - 0.2.89
    - 0.2.90
    - 0.2.91
    - 0.2.92
    - 0.2.93
  - dependency-name: syn
    versions:
    - 1.0.60
    - 1.0.61
    - 1.0.62
    - 1.0.63
    - 1.0.64
    - 1.0.66
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
    - 1.0.63
  - dependency-name: tinyvec
    versions:
    - 1.1.1
  - dependency-name: thread_local
    versions:
    - 1.1.2
  - dependency-name: regex-syntax
    versions:
    - 0.6.22
  - dependency-name: quote
    versions:
    - 1.0.8
  - dependency-name: cc
    versions:
    - 1.0.66
