[package]
name = "arbre_clair"
version = "0.1.0"
authors = ["Aedius"]
edition = "2018"

[dependencies]
ctrlc = "3.1.7"
lazy_static = "1.4.0"
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tiny_http = "0.8.0"
